version: '3'
name: 'mystay'
services:
  postgres:
    image: postgres:latest
    container_name: postgres2
    environment:
      POSTGRES_USER: mystay
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mystay_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

